theme: dark

identity_validation:
  reset_password:
    jwt_secret: "${VAR_LOCAL_AUTHELIA_JWT_SECRET}"
    jwt_lifespan: "5 minutes"
    jwt_algorithm: "HS256"

log:
  level: debug

totp:
  issuer: ${VAR_GLOBAL_AUTHELIA_SUBDOMAIN}.${VAR_GLOBAL_ROOT_DOMAIN}

authentication_backend:
  password_reset.disable: true
  refresh_interval: 5m
  file:
    path: "/config/users_database.yml"
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: "deny"
  rules:
    - domain: ${VAR_GLOBAL_WHOAMI_UNSECURE_SUBDOMAIN}.${VAR_GLOBAL_ROOT_DOMAIN}
      policy: bypass
    - domain: ${VAR_GLOBAL_WHOAMI_SECURE_SUBDOMAIN}.${VAR_GLOBAL_ROOT_DOMAIN}
      policy: one_factor
    - domain:
        - "${VAR_GLOBAL_ROOT_DOMAIN}"
        - "*.${VAR_GLOBAL_ROOT_DOMAIN}"
      policy: two_factor

session:
  secret: "${VAR_LOCAL_AUTHELIA_SESSION_SECRET}"
  cookies:
    - name: authelia_session
      domain: ${VAR_GLOBAL_ROOT_DOMAIN}
      authelia_url: https://${VAR_GLOBAL_AUTHELIA_SUBDOMAIN}.${VAR_GLOBAL_ROOT_DOMAIN}
      default_redirection_url: https://${VAR_GLOBAL_ROOT_DOMAIN}
      expiration: "1 hour"
      inactivity: "5 minutes"
      remember_me: "1 month"

regulation:
  max_retries: 3
  find_time: "5 minutes"
  ban_time: "1 hour"

storage:
  encryption_key: "${VAR_LOCAL_AUTHELIA_STORAGE_ENCRYPTION_KEY}"
  local:
    path: /var/authelia/db.sqlite3

notifier:
  filesystem:
    filename: /var/authelia/notification.txt

identity_providers:
  oidc:
    enable_client_debug_messages: true
    hmac_secret: "${VAR_LOCAL_AUTHELIA_OIDC_HMAC_SECRET}"
    jwks:
      # prettier-ignore
      - key: {{ secret "/config/keys/oidc-jwks/private.pem" | mindent 10 "|" | msquote }}
    clients:
      # Generate client_secret's with: docker run authelia/authelia:latest authelia crypto hash generate pbkdf2 --variant sha512 --random --random.length 72 --random.charset rfc3986
      # Were client_secret is the 'Digest', and 'Random Password' you give to the client.
      - client_id: ${VAR_LOCAL_AUTHELIA_OIDC_PORTAINER_CLIENT_ID}
        client_name: "Portainer"
        client_secret: "${VAR_LOCAL_AUTHELIA_OIDC_PORTAINER_CLIENT_SECRET}"
        public: false
        authorization_policy: "two_factor"
        require_pkce: false
        pkce_challenge_method: ""
        redirect_uris:
          - "https://${VAR_GLOBAL_PORTAINER_SUBDOMAIN}.${VAR_GLOBAL_ROOT_DOMAIN}"
        scopes:
          - "openid"
          - "profile"
          - "groups"
          - "email"
        response_types:
          - "code"
        grant_types:
          - "authorization_code"
        access_token_signed_response_alg: "none"
        userinfo_signed_response_alg: "none"
        token_endpoint_auth_method: "client_secret_post"
        consent_mode: "pre-configured"
        pre_configured_consent_duration: "1 year"
      - client_id: ${VAR_LOCAL_AUTHELIA_OIDC_GUACAMOLE_CLIENT_ID}
        client_name: "Apache Guacamole"
        public: true
        authorization_policy: "two_factor"
        require_pkce: false
        pkce_challenge_method: ""
        redirect_uris:
          - "https://${VAR_GLOBAL_GUACAMOLE_SUBDOMAIN}.${VAR_GLOBAL_ROOT_DOMAIN}"
          - "https://${VAR_GLOBAL_GUACAMOLE_SUBDOMAIN}.${VAR_GLOBAL_ROOT_DOMAIN}/guacamole"
        scopes:
          - "openid"
          - "profile"
          - "groups"
          - "email"
        response_types:
          - "id_token"
        grant_types:
          - "implicit"
        access_token_signed_response_alg: "none"
        userinfo_signed_response_alg: "none"
        token_endpoint_auth_method: "none"
        consent_mode: "pre-configured"
        pre_configured_consent_duration: "1 year"
      - client_id: ${VAR_LOCAL_AUTHELIA_OIDC_KOMODO_CLIENT_ID}
        client_name: "Komodo"
        client_secret: "${VAR_LOCAL_AUTHELIA_OIDC_KOMODO_CLIENT_SECRET}"
        public: false
        require_pkce: true
        pkce_challenge_method: "S256"
        authorization_policy: "two_factor"
        redirect_uris:
          - "https://${VAR_GLOBAL_KOMODO_SUBDOMAIN}.${VAR_GLOBAL_ROOT_DOMAIN}/auth/oidc/callback"
        scopes:
          - "openid"
          - "profile"
          - "email"
        response_types:
          - "code"
        grant_types:
          - "authorization_code"
        access_token_signed_response_alg: "none"
        userinfo_signed_response_alg: "none"
        token_endpoint_auth_method: "client_secret_basic"
        consent_mode: "pre-configured"
        pre_configured_consent_duration: "1 year"
