# service-komodo

services:
  service-komodo-mongo:
    image: mongo
    container_name: service-komodo-mongo
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - hotbox
    command: --quiet --wiredTigerCacheSizeGB 0.25
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${VAR_LOCAL_KOMODO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${VAR_LOCAL_KOMODO_DB_PASSWORD}
    volumes:
      - service-komodo-mongo-data:/data/db
      - service-komodo-mongo-config:/data/configdb
    labels:
      komodo.skip:

  service-komodo-core:
    image: ghcr.io/moghtech/komodo-core:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    container_name: service-komodo-core
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - hotbox
    ports:
      - 9120:9120
    depends_on:
      - service-komodo-mongo
    env_file:
      - ./.env.config
      - ./.env
    environment:
      KOMODO_DATABASE_ADDRESS: service-komodo-mongo:27017
      KOMODO_DATABASE_USERNAME: ${VAR_LOCAL_KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${VAR_LOCAL_KOMODO_DB_PASSWORD}
    volumes:
      - service-komodo-core-repo-cache:/repo-cache
    labels:
      komodo.skip:
      traefik.enable: "true"
      traefik.http.routers.service-komodo-core.rule: "Host(`${VAR_LOCAL_KOMODO_HOST}`)"
      traefik.http.routers.service-komodo-core.entrypoints: "websecure"
      traefik.http.routers.service-komodo-core.tls: "true"
      traefik.http.routers.service-komodo-core.tls.certresolver: "cloudflare"
      traefik.http.services.service-komodo-core.loadbalancer.server.port: "9120"

  service-komodo-periphery:
    image: ghcr.io/moghtech/komodo-periphery:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    container_name: service-komodo-periphery
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - hotbox
    env_file:
      - ./.env.config
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc # Allow Periphery to see processes outside of container
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
    labels:
      komodo.skip:

# Change later
networks:
  hotbox:
    external: true

volumes:
  service-komodo-mongo-data:
  service-komodo-mongo-config:
  service-komodo-core-repo-cache:
