services:
  #Pterodactyl Panel
  service-pterodactyl-panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: service-pterodactyl-panel
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - service-pterodactyl-db
      - service-pterodactyl-cache
    networks:
      - hotbox
    environment:
      APP_URL: "https://${VAR_GLOBAL_PTERODACTYL_SUBDOMAIN}.${VAR_GLOBAL_ROOT_DOMAIN}"
      APP_TIMEZONE: "${VAR_GLOBAL_TIMEZONE}"
      APP_SERVICE_AUTHOR: "${VAR_LOCAL_PTERODACTYL_SERVICE_AUTHOR}"
      MAIL_FROM_ADDRESS: "${VAR_LOCAL_PTERODACTYL_SMTP_SENDER}"
      MAIL_FROM_NAME: "${VAR_LOCAL_PTERODACTYL_SMTP_SENDER_NAME}"
      MAIL_DRIVER: "smtp"
      MAIL_HOST: "${VAR_LOCAL_PTERODACTYL_SMTP_SERVER_HOST}"
      MAIL_PORT: "${VAR_LOCAL_PTERODACTYL_SMTP_SERVER_PORT}"
      MAIL_USERNAME: "${VAR_LOCAL_PTERODACTYL_SMTP_USERNAME}"
      MAIL_PASSWORD: "${VAR_LOCAL_PTERODACTYL_SMTP_PASSWORD}"
      MAIL_ENCRYPTION: ${VAR_LOCAL_PTERODACTYL_SMTP_ENCRYPTION}
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "service-pterodactyl-cache"
      DB_HOST: "service-pterodactyl-db"
      DB_PORT: "3306"
      DB_PASSWORD: "${VAR_LOCAL_PTERODACTYL_MYSQL_USER_PASSWORD}"
      DB_DATABASE: "${VAR_LOCAL_PTERODACTYL_MYSQL_DATABASE}"
      DB_USERNAME: "${VAR_LOCAL_PTERODACTYL_MYSQL_USER}"
    volumes:
      - "service-pterodactyl-panel-var:/app/var/"
      - "service-pterodactyl-panel-nginx:/etc/nginx/http.d/"
      - "service-pterodactyl-panel-certs:/etc/letsencrypt/"
      - "service-pterodactyl-panel-logs:/app/storage/logs"
    labels:
      traefik.enable: "true"
      traefik.http.routers.service-pterodactyl-panel.rule: "Host(`${VAR_GLOBAL_PTERODACTYL_SUBDOMAIN}.${VAR_GLOBAL_ROOT_DOMAIN}`)"
      traefik.http.routers.service-pterodactyl-panel.entrypoints: "websecure"
      traefik.http.routers.service-pterodactyl-panel.tls: "true"
      traefik.http.routers.service-pterodactyl-panel.tls.certresolver: "cloudflare"
      traefik.http.services.service-pterodactyl-panel.loadbalancer.server.port: "80"

  #Pterodactyl Database
  service-pterodactyl-db:
    image: mariadb:10.5
    container_name: service-pterodactyl-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    security_opt:
      - no-new-privileges:true
    networks:
      - hotbox
    environment:
      MYSQL_USER: "${VAR_LOCAL_PTERODACTYL_MYSQL_USER}"
      MYSQL_PASSWORD: "${VAR_LOCAL_PTERODACTYL_MYSQL_USER_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${VAR_LOCAL_PTERODACTYL_MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${VAR_LOCAL_PTERODACTYL_MYSQL_DATABASE}"
    volumes:
      - "service-pterodactyl-db-data:/var/lib/mysql"

  #Pterodactyl Cache
  service-pterodactyl-cache:
    image: redis:alpine
    container_name: service-pterodactyl-cache
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - hotbox

  #Pterodactyl Wing
  service-pterodactyl-wing:
    image: ghcr.io/pterodactyl/wings:latest
    container_name: service-pterodactyl-wing
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - pterodactyl0
      - hotbox
    # ports:
    # game server port range
    # - "25560-25569:25560-25569"
    tty: true
    environment:
      TZ: "${VAR_GLOBAL_TIMEZONE}"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      - "service-pterodactyl-wing-etc:/etc/pterodactyl/"
      - "service-pterodactyl-wing-lib:/var/lib/pterodactyl/"
      - "service-pterodactyl-wing-log:/var/log/pterodactyl/"
      - "service-pterodactyl-wing-temp:/tmp/pterodactyl/"
    labels:
      traefik.enable: "true"
      traefik.network: "hotbox"
      traefik.http.routers.service-pterodactyl-wing.rule: "Host(`${VAR_GLOBAL_PTERODACTYL_WING_SUBDOMAIN}.${VAR_GLOBAL_ROOT_DOMAIN}`)"
      traefik.http.routers.service-pterodactyl-wing.entrypoints: "websecure"
      traefik.http.routers.service-pterodactyl-wing.tls: "true"
      traefik.http.routers.service-pterodactyl-wing.tls.certresolver: "cloudflare"
      traefik.http.services.service-pterodactyl-wing.loadbalancer.server.port: "8089"
      traefik.http.routers.service-pterodactyl-wing-sftp.rule: "HostSNI(`${VAR_GLOBAL_PTERODACTYL_WING_SUBDOMAIN}.${VAR_GLOBAL_ROOT_DOMAIN}`)"
      traefik.http.routers.service-pterodactyl-wing-sftp.entrypoints: "sftp"
      traefik.http.routers.service-pterodactyl-wing-sftp.tls: "true"
      traefik.http.routers.service-pterodactyl-wing-sftp.tls.certresolver: "cloudflare"
      traefik.http.services.service-pterodactyl-wing-sftp.loadbalancer.server.port: "2022"

networks:
  hotbox:
    external: true
  pterodactyl0:
    name: pterodactyl0
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: pterodactyl0

volumes:
  service-pterodactyl-panel-var:
  service-pterodactyl-panel-nginx:
  service-pterodactyl-panel-certs:
  service-pterodactyl-panel-logs:
  service-pterodactyl-db-data:
  service-pterodactyl-wing-etc:
  service-pterodactyl-wing-lib:
  service-pterodactyl-wing-log:
  service-pterodactyl-wing-temp:
