# service-code

services:
  service-code-vscode:
    image: lscr.io/linuxserver/code-server:latest
    container_name: service-code-vscode
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - hotbox
    environment:
      - PUID=${VAR_PUID}
      - PGID=${VAR_PGID}
      - TZ=${VAR_TZ}
      - HASHED_PASSWORD=${VAR_PASSWORD_HASH}
      - PWA_APPNAME=${VAR_APPNAME}
      - PROXY_DOMAIN=${VAR_GLOBAL_CODE_SERVER_SUBDOMAIN}.${VAR_GLOBAL_ROOT_DOMAIN}
      - DEFAULT_WORKSPACE=/home/coder/dev
    volumes:
      - service-code-vscode-config:/config
      - service-code-vscode-dev:/home/coder/dev
    labels:
      traefik.enable: "true"
      traefik.http.routers.service-code-vscode.rule: "Host(`${VAR_GLOBAL_CODE_SERVER_SUBDOMAIN}.${VAR_GLOBAL_ROOT_DOMAIN}`)"
      traefik.http.routers.service-code-vscode.entrypoints: "websecure"
      traefik.http.routers.service-code-vscode.tls: "true"
      traefik.http.routers.service-code-vscode.tls.certresolver: "cloudflare"
      traefik.http.services.service-code-vscode.loadbalancer.server.port: "8443"
      traefik.http.routers.service-code-vscode.middlewares: "service-proxy-authelia@docker"

networks:
  hotbox:
    external: true

volumes:
  service-code-vscode-config:
  service-code-vscode-dev:
