# service-torrent

services:
  service-torrent-gluetun:
    image: qmcgaw/gluetun
    container_name: service-torrent-gluetun
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - hotbox
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - service-torrent-gluetun-config:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VAR_LOCAL_VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VAR_LOCAL_VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${VAR_LOCAL_WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=${VAR_LOCAL_SERVER_COUNTRIES}
    labels:
      traefik.enable: "true"
      traefik.http.routers.service-torrent-overseerr.rule: "Host(`${VAR_GLOBAL_TORRENT_CLIENT_SUBDOMAIN}.${VAR_GLOBAL_ROOT_DOMAIN}`)"
      traefik.http.routers.service-torrent-overseerr.entrypoints: "websecure"
      traefik.http.routers.service-torrent-overseerr.tls: "true"
      traefik.http.routers.service-torrent-overseerr.tls.certresolver: "cloudflare"
      traefik.http.services.service-torrent-overseerr.loadbalancer.server.port: "9091"
      traefik.http.routers.service-torrent-overseerr.middlewares: "service-proxy-authelia@docker"

  service-torrent-transmission:
    image: linuxserver/transmission
    container_name: service-torrent-transmission
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: "service:service-torrent-gluetun"
    depends_on:
      - service-torrent-gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${VAR_GLOBAL_TIMEZONE}
    volumes:
      - service-torrent-transmission-config:/config
      - ${VAR_LOCAL_DOWNLOAD_PATH}:/downloads

  service-torrent-overseerr:
    image: sctx/overseerr:latest
    container_name: service-torrent-overseerr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - hotbox
    environment:
      - LOG_LEVEL=info
      - TZ=${VAR_GLOBAL_TIMEZONE}
    volumes:
      - service-torrent-overseerr-config:/app/config
    labels:
      traefik.enable: "true"
      traefik.http.routers.service-torrent-overseerr.rule: "Host(`${VAR_GLOBAL_OVERSEERR_SUBDOMAIN}.${VAR_GLOBAL_ROOT_DOMAIN}`)"
      traefik.http.routers.service-torrent-overseerr.entrypoints: "websecure"
      traefik.http.routers.service-torrent-overseerr.tls: "true"
      traefik.http.routers.service-torrent-overseerr.tls.certresolver: "cloudflare"
      traefik.http.services.service-torrent-overseerr.loadbalancer.server.port: "5055"

  service-torrent-sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: service-torrent-sonarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - hotbox
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${VAR_GLOBAL_TIMEZONE}
    volumes:
      - service-torrent-sonarr-config:/config
      - ${VAR_LOCAL_DOWNLOAD_PATH}:/downloads
      - ${VAR_LOCAL_TV_PATH}:/tv

  service-torrent-radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: service-torrent-radarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - hotbox
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${VAR_GLOBAL_TIMEZONE}
    volumes:
      - service-torrent-radarr-config:/config
      - ${VAR_LOCAL_DOWNLOAD_PATH}:/downloads
      - ${VAR_LOCAL_MOVIES_PATH}:/movies

networks:
  hotbox:
    external: true

volumes:
  service-torrent-gluetun-config:
  service-torrent-transmission-config:
  service-torrent-overseerr-config:
  service-torrent-sonarr-config:
  service-torrent-radarr-config:
